- name: Copy and Start Go on Linux Server
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Copy Go Binary
      copy:
        src: ../todoapp
        dest: /home/alv
        mode: "0755"

    - name: Start Go Application
      command: ./todoapp